account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout',)
]

pyq/urls.py
from django.urls import path
from . import views

app_name = 'pyq'
urlpatterns = [
    path('', views.index, name='index'),

    # path('<str:user_sid>/post_add', views.post_add, name='post_add'),
    # path('<str:user_sid>/<int:post_id>/post_delete', views.post_delete, name='post_delete'),
    # path('<str:user_sid>/<int:post_id>/post_edit', views.post_edit, name='post_edit'),
    # path('<str:user_sid>/post_edit_add', views.post_edit_add, name='post_edit_add'),
    path('<int:pages>/<int:post_id>/post', views.post_action, name='post_action'),
]

pyqproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('pyq/', include('pyq.urls')),
]

account/models.py
from django.db import models
from django.db.models import Q


# Create your models here.
class User(models.Model):
    sid = models.CharField(max_length=50, unique=1)
    username = models.CharField(max_length=50, unique=1)
    password = models.CharField(max_length=50)
    permission = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    @classmethod
    def verify_login_info(cls, user_for_login, password):
        user_result = User.objects.filter(Q(sid=user_for_login) | Q(username=user_for_login))
        if len(user_result) > 0:
            if user_result[0].password == password:
                return '', user_result
            else:
                err = "Please input the correct password!"
        else:
            err = "The user doesn't exist!"
        return err, user_result

    @classmethod
    def user_add(cls, sid, username, password):
        u = User(sid=sid, username=username, password=password)
        u.save()

    @classmethod
    def verify_register_info(cls, sid, username, password, password1):
        err = ''
        user_1 = User.objects.filter(sid=sid)
        user_2 = User.objects.filter(username=username)
        if len(user_1) > 0:
            err = "The Student ID is already exist!"
        elif len(user_2) > 0:
            err = "The Username is already exist!"
        elif password != password1:
            err = "The passwords are inconsistent!"
        return err

pyq/models.py
from django.db import models
from django.shortcuts import render

from account.models import User

per_post = 6


# Create your models here.
class Post(models.Model):
    pid = models.AutoField(primary_key=True)
    user_now = models.ForeignKey(User, on_delete=models.CASCADE)
    context = models.TextField()
    created_time = models.DateTimeField('Created', auto_now_add=True)
    edit_time = models.DateTimeField('Edit', auto_now=True)

    def __str__(self):
        return self.context

    @classmethod
    def post_add(cls, user_login, context):
        p = Post(user_now=user_login, context=context)
        p.save()

    @classmethod
    def post_edit(cls, post_now, context):
        post_now.context = context
        post_now.save()

    @classmethod
    def count_pages(cls, pages):
        tot = Post.objects.count()
        if tot <= pages * per_post:
            return 0
        else:
            return 1

    @classmethod
    def show(cls, request, user_login, pages):
        more_pages = Post.count_pages(pages)
        if more_pages:
            posts = list(Post.objects.all())[-1:-(per_post * pages + 1):-1]
        else:
            posts = list(Post.objects.all())[::-1]
        return render(request, 'pyq/index.html', {
            'posts': posts,
            'user_login': user_login,
            'pages': pages,
            'more_pages': more_pages,
        })

account/forms.py
from django import forms


class UserFormLogin(forms.Form):
    user_for_login = forms.CharField(label='username', max_length=50)
    password = forms.CharField(label='password', widget=forms.PasswordInput())


class UserFormRegister(forms.Form):
    sid = forms.CharField(label='Student ID', max_length=50)
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    password1 = forms.CharField(label='Password Again', widget=forms.PasswordInput())

pyq/forms.py
from django import forms
from .models import Post


class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['context']

account/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

from .models import User
from .forms import UserFormLogin, UserFormRegister
import hashlib


def md5(tmp):
    m = hashlib.md5()
    m.update(tmp.encode("utf8"))
    return m.hexdigest()


def check_session(func):
    def wrapper(request, *aaa, **kv):
        user_info = request.session.get('myUser', None)
        if user_info != list(kv.values())[0]:
            return HttpResponseRedirect(reverse('account:login'))
        return func(request, *aaa, **kv)
    return wrapper


def login(request):
    err = ''
    if request.method == "POST":
        uf = UserFormLogin(request.POST)
        if uf.is_valid():
            user_for_login = uf.cleaned_data['user_for_login']
            password = uf.cleaned_data['password']
            err, user_result = User.verify_login_info(user_for_login, password)
            if err == '':
                request.session['myUser'] = user_result[0].sid
                return HttpResponseRedirect(reverse('pyq:index'))
    else:
        uf = UserFormLogin()
    return render(request, 'account/login2.html', {
        'uf': uf,
        'error_message': err,
    })


def logout(request):
    try:
        del request.session['myUser']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('account:login'))


def register(request):
    err = ''
    if request.method == 'POST':
        uf = UserFormRegister(request.POST)
        if uf.is_valid():
            sid = uf.cleaned_data['sid']
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            password1 = uf.cleaned_data['password1']
            err = User.verify_register_info(sid, username, password, password1)
            if err == '':
                User.user_add(sid, username, password)
                return HttpResponseRedirect(reverse('account:login'))
    else:
        uf = UserFormRegister()
    return render(request, 'account/register.html', {
            'uf': uf,
            'error_message': err,
    })

pyq/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse


from .forms import PostForms
from .models import Post
from account.models import User
from account.views import check_session


def get_user_from_request(request):
    user_sid = request.session.get('myUser', None)
    if not user_sid:
        return None
    user_login = get_object_or_404(User, sid=user_sid)
    return user_login


# @check_session
def index(request):
    user_login = get_user_from_request(request)
    if not user_login:
        return HttpResponseRedirect(reverse('account:login'))
    return Post.show(request, user_login, 1)


# @check_session
def post_action(request, pages, post_id):
    user_login = get_user_from_request(request)
    if not user_login:
        return HttpResponseRedirect(reverse('account:login'))
    if request.method == 'POST':
        if request.POST['type_change'] == 'add':
            post_form = PostForms(request.POST)
            if post_form.is_valid():
                context = post_form.cleaned_data['context']
                Post.post_add(user_login, context)
        elif request.POST['type_change'] == 'delete':
            post_now = get_object_or_404(Post, pk=post_id)
            if user_login == post_now.user_now or user_login.permission:
                post_now.delete()
        elif request.POST['type_change'] == 'edit_add':
            post_now = get_object_or_404(Post, pk=post_id)
            if user_login == post_now.user_now:
                post_form = PostForms(request.POST)
                if post_form.is_valid():
                    context = post_form.cleaned_data['context']
                    Post.post_edit(post_now, context)
        elif request.POST['type_change'] == 'load_more':
            pages += 1
    return Post.show(request, user_login, pages)

pyq/templates/pyq/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user_login.username }}</title>
</head>
<body>
    <h1>{{ user_login.username }}</h1>
    <form action="{% url 'pyq:post_action' pages post_edit.pid %}" method="post">
        {% csrf_token %}
        <div>
            <label><textarea name="context" placeholder="what do you want to post?">{{ post_edit.context }}</textarea></label>
            <input type="hidden" name="type_change" value="edit_add"/>
            <!--<input type="hidden" name="post_id" value=" post_edit.id " />-->
            <input type="submit" value="submit" />
        </div>
    </form>
</body>
</html>

pyq/templates/pyq/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user_login.username }}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'pyq/index.css' %}" />
    <script type="text/javascript" src="{% static 'account/jquery-3.3.1.js' %}"></script>

    <script>
        $(document).ready(function() {
            $(".edit_button").click(function(){
                var tmp = '#' + $(this).attr('name');
                $(tmp+'0').css({'display': 'none'});
                $(tmp).css({'display': 'block'});
            });
        });
    </script>
</head>

<body class="index">

<h1>{{ user_login.username }}</h1>
<form action="{% url 'account:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Log Out" />
</form>
<br>

<form action="{% url 'pyq:post_action' pages user_login.id %}" method='post' enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <textarea style="" name="context" placeholder="What do you want to post?" rows="3" cols='120'></textarea>
        <input type="hidden" name="type_change" value="add"/>
    </div>
    <div>
        <input type="submit" value="submit" style="float: right"/><br>
    </div>
</form>


<hr>


<div>
    <div id="post_list_item">
        {% for post in posts %}
            <div class="fieldset">
                {% if post.user_now == user_login %}
                    <div class="self_post">
                        <p class="edit_content" id="post{{ post.pid }}0">
                            <content>{{ post.context }}&nbsp &nbsp &nbsp</content><br>
                            created: {{ post.created_time }}&nbsp &nbsp &nbsp
                            {% if post.edit_time != post.created_time %}
                                edited
                            {% endif %}
                        </p>
                        <div class="edit_add_content" id="post{{ post.pid }}">
                            <form action="{% url 'pyq:post_action' pages post.pid %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label><textarea name="context" placeholder="what do you want to post?">{{ post.context }}</textarea></label>
                                <input type="hidden" name="type_change" value="edit_add"/>
                                <input type="submit" value="submit" />
                            </div>
                            </form>
                        </div>
                    </div>
                {% else %}
                    <div class="not_self_post">
                    <h1><span>{{ post.user_now }}</span></h1>
                    <p><content>&nbsp &nbsp &nbsp{{ post.context }}</content><br>
                        created: {{ post.created_time }}&nbsp &nbsp &nbsp
                        {% if post.edit_time != post.created_time %}
                            edited
                        {% endif %}
                    </p>
                    </div>
                {% endif %}
                    <table align="center">
                    <tr>
                    <td>
                    {% if post.user_now == user_login %}
                        <button class="edit_button" name="post{{ post.pid }}">edit</button>
                    {% endif %}
                    </td>
                    <td>
                    {% if post.user_now == user_login or user_login.permission %}
                        <form action="{% url 'pyq:post_action' pages post.pid %}" method="post">
                            {% csrf_token %}
                            <button onclick="return DeleteConfirmFunc()">Delete</button>
                            <script>
                                function DeleteConfirmFunc()
                                {
                                    return confirm("Are u sure to DELETE?");
                                }
                            </script>
                            <input type="hidden" name="type_change" value="delete"/>
                        </form>
                    {% endif %}
                    </td>
                    </tr>
                    </table>
            </div>

        {% endfor %}
    </div>
</div>

<div>
    {% if more_pages %}
        <form action="{% url 'pyq:post_action' pages user_login.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="load more">
            <input type="hidden" name="type_change" value="load_more">
        </form>
    {% else %}
        <p>Already the last post</p>
    {% endif %}
</div>

</body>
</html>